# Generated by Django 4.2 on 2023-04-18 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 12, 28, 41, 12077, tzinfo=datetime.timezone.utc)),
        ),
    ]
